pipeline {

   agent none

   stages {

      stage('build') {
        agent {
          docker {
            image 'maven:3.6.1-jdk-8-slim'
            args '-v m2:/root/.m2'
          }
        }

         when {
           changeset "java/cmad-ms-users/**"
         }
         steps {
            echo 'compiling users service'
            dir('java/cmad-ms-users'){
              sh 'mvn compile'
            }
         }
      }

      stage('test') {
        agent {
          docker {
            image 'maven:3.6.1-jdk-8-slim'
            args '-v m2:/root/.m2'
          }
        }

         when {
          changeset "java/cmad-ms-users/**"
         }
         steps {
            echo 'running unit tests on users service'
            dir('java/cmad-ms-users'){
              sh 'mvn clean test'
            }
         }
      }

      stage('docker-package'){
          agent any
          steps{
            echo 'Packaging users app with docker'
            script{
              docker.withRegistry('https://index.docker.io/v1/', 'dockerlogin') {
                  def usersImage = docker.build("initcron/users:v${env.BUILD_ID}", "./java/cmad-ms-users")
                  usersImage.push()
                  usersImage.push("latest")
              }
            }
          }
      }

      stage('package') {
        agent {
          docker {
            image 'maven:3.6.1-jdk-8-slim'
            args '-v m2:/root/.m2'
          }
        }

         when {
           changeset "java/cmad-ms-users/**"
           branch 'master'
         }
         steps {
            echo 'packaging users app'
            dir('java/cmad-ms-users'){
              sh 'mvn package -DskipTests'
            }
         }
      }
   }
}
